### ISSUE TITLE
Essential Matrix estimation for equi-rectangular projection cameras

### ISSUE THREAD

**Issue by rishchou** [danini/magsac#12]
Is there a way to estimate Essential Matrix using DefaultEssentialMatrixEstimator() for cameras which don't have camera intrinsic matrices (for eg, 360 degree cameras)

**Comment by danini** [comment]
There is for sure a way to integrate such a solver. There are two things which you need to do:
- Implement a new estimator, e.g., like the EssentialMatrixEstimator class. 
- Implement the solver which estimates the model from a given set of points (e.g., FivePointEssentialMatrixSolver).

If you send a solver that solves that problem I make it work with MAGSAC++ if that is easier for you.
