### ISSUE TITLE
Very verbose MAGSAC++ - is it possible to turn it off?

### ISSUE THREAD

**Issue by anthony-khong** [danini/magsac#17]
Hello. Whenever I run `pymagsac.findHomography' with `use_magsac_plus_plus=True` I always get really verbose prints:

```
Setting the core number for MAGSAC++ is deprecated.
Setting the partition number for MAGSAC++ is deprecated.
```

Is there a way to suppress this? I believe the prints are coming from [here](https://github.com/danini/magsac/blob/master/src/pymagsac/include/magsac.h#L100), but it's been hard-coded [here](https://github.com/danini/magsac/blob/master/src/pymagsac/src/magsac_python.cpp#L33).

Perhaps the following lines (L33-34) can be deleted if `use_magsac_plus_plus` is false?

```
    magsac->setCoreNumber(1); // The number of cores used to speed up sigma-consensus
    magsac->setPartitionNumber(partition_num); // The number partitions used for speeding up sigma consensus. As the value grows, the algorithm become slower and, usually, more accurate.
```

I'd be happy to create a PR if you think it'd be useful.

**Comment by danini** [comment]
I have just added GLOG, so now it can be turned off.

**Comment by anthony-khong** [comment]
Hi @danini, I wonder there are additional dependencies to the library that have not been documented (glog and gflags)? I believe it may be your most recent change.

I was building my Docker image using this [Dockerfile](https://github.com/anthony-khong/magsac/blob/docker-install-test/Dockerfile-old), but I recently had to change it to this [Dockerfile](https://github.com/anthony-khong/magsac/blob/docker-install-test/Dockerfile) with more steps. Is there a more concise way to do this?

Also, in light of this, would you take a PR to add a GitHub Action pipeline to install the C++ and Python libraries?

**Comment by danini** [comment]
Hi, yes it is right. I just added glog and gflags a few days back.
I have never in my life wrote Dockerfile, so I cannot help with that :)
I will look into this GitHub Action pipeline, thank you for the suggestion.
