### ISSUE TITLE
example_homography running occur error

### ISSUE THREAD

**Issue by xjpeng1** [danini/magsac#19]
Hi, @danini and @ducha-aiki ,

Thanks for sharing your great work!

Unfortunatelly, issues raised when I run the example_homography.I never modify the content of this file.

Appended is the error:
TypeError: findHomography(): incompatible function arguments. The following argument types are supported:
    1. (x1y1: numpy.ndarray[float64], x2y2: numpy.ndarray[float64], w1: float, h1: float, w2: float, h2: float, use_magsac_plus_plus: bool=True, sigma_th: float=1.0, conf: float=0.99, max_iters: int=1000, partition_num: int=5) -> tuple

**Comment by lhaippp** [comment]
Hi did you resolve the issue? 
And how did you fix it?

Thanks
