### ISSUE TITLE
Just out of curiosity

### ISSUE THREAD

**Issue by fb82** [danini/magsac#2]
Hi,
your paper is very interesting, thanks for sharing the code!

Just out of curiosity. In some of my old experiments (see "[noRANSAC for fundamental matrix estimation](http://www.bmva.org/bmvc/2011/proceedings/paper98/paper98.pdf)", Table 5), I found that the geometric epipolar error (i.e. sqrt(e12^2+e21^2)) is usually more robust than the symmetric epipolar error. Did you also try some kind of similar error with MAGSAC?

Thanks again,
Fabio

**Comment by danini** [comment]
It is like that now, however, a long time has passed since your question :)
