### ISSUE TITLE
Is this algorithm suitable for find SIM3 matrix from 3D points pairs?

### ISSUE THREAD

**Issue by arenas7307979** [danini/magsac#25]
hii, thank for your sharing, 
Many of the strategies for optimizing result  of the transformation estimation in the image problem.
the algorithm suitable for find SIM3 matrix from two group 3D points pair in coordinate transforamton problem?

**Comment by danini** [comment]
If this is still relevant, you can find example code in 
https://github.com/danini/magsac/blob/master/examples/example_rigid_transform.ipynb
