### ISSUE TITLE
code for essential matrix estimation

### ISSUE THREAD

**Issue by weiweisun2018** [danini/magsac#3]
Hello authors,
Thanks much for sharing the code.
Actually, I am looking for the code for estimating the essential matrix but fail to figure out. Do you release the code for essential matrix as described in the paper?

**Comment by danini** [comment]
I am now re-implementing most of the things together with the essential matrix estimation. It still needs a few days to finish but is coming soon.

**Comment by weiweisun2018** [comment]
Thanks! looking forward to the code :))

**Comment by Skydes** [comment]
While you're at it, it would be awesome to have a clean OpenCV-like Python interface with [pybind11](https://github.com/pybind/pybind11) :) This would definitely help widespread adoption.

**Comment by danini** [comment]
@Skydes It is done :) I will upload it together or slightly after the revised C++ source.

**Comment by weiweisun2018** [comment]
Great jobs! @danini It will definitely be appreciated!! I tried to write one python wrapper. Looks ugly though.

**Comment by Skydes** [comment]
@danini Awesome! Looking forward to it.

**Comment by danini** [comment]
Hey @Skydes, you can find it here: https://github.com/ducha-aiki/pymagsac

**Comment by Skydes** [comment]
@danini Great, thanks for letting me know! And thanks @ducha-aiki for the wrapper :)
