### ISSUE TITLE
Compare to A-Contrario model

### ISSUE THREAD

**Issue by cdcseacave** [danini/magsac#7]
Interesting paper, Dani, but I'm very surprised you do not compare your method to existing parameter-free RANSAC methods. For example it would be very useful to compare MAGSAC against the very successful method developed by @pmoulon:
P. Moulon, P. Monasse, R. Marlet. Adaptive Structure from Motion with a contrario mode estimation. ACCV 2012

**Comment by danini** [comment]
Thank you! That comparison is in the paper in Table 1. 
http://openaccess.thecvf.com/content_CVPR_2019/papers/Barath_MAGSAC_Marginalizing_Sample_Consensus_CVPR_2019_paper.pdf

**Comment by cdcseacave** [comment]
Thank you! I was speaking about `Figure 3`, but indeed `Table 1` is better than nothing.
